-- down migration

DROP TABLE IF EXISTS ingredients CASCADE;
DROP TABLE IF EXISTS mods CASCADE;
DROP TABLE IF EXISTS ammo CASCADE;
DROP TABLE IF EXISTS clothing_item CASCADE;
DROP TABLE IF EXISTS weapon_item CASCADE;
DROP TABLE IF EXISTS category CASCADE;