ALTER TABLE weapon_item DROP COLUMN IF EXISTS description;
ALTER TABLE weapon_item DROP COLUMN IF EXISTS shortname;
ALTER TABLE weapon_item DROP COLUMN IF EXISTS capacity;
ALTER TABLE weapon_item DROP COLUMN IF EXISTS time_to_craft;

ALTER TABLE ammo DROP COLUMN IF EXISTS icon;
ALTER TABLE mods DROP COLUMN IF EXISTS icon;
ALTER TABLE ingredients DROP COLUMN IF EXISTS amount;
ALTER TABLE ingredients DROP COLUMN IF EXISTS icon;
