ALTER TABLE weapon_item ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE weapon_item ADD COLUMN IF NOT EXISTS shortname VARCHAR(255);
ALTER TABLE weapon_item ADD COLUMN IF NOT EXISTS capacity INTEGER;
ALTER TABLE weapon_item ADD COLUMN IF NOT EXISTS time_to_craft INTEGER;

ALTER TABLE ammo ADD COLUMN IF NOT EXISTS icon VARCHAR(255);
ALTER TABLE mods ADD COLUMN IF NOT EXISTS icon VARCHAR(255);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS amount INTEGER;
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS icon VARCHAR(255);
